gui:
  theme:
    activeBorderColor:
      - '#fabd2f'
      - bold
    inactiveBorderColor:
      - '#7c6f64'
    optionsTextColor:
      - '#fabd2f'
    selectedLineBgColor:
      - '#282828'
    cherryPickedCommitBgColor:
      - '#1d2021'
    cherryPickedCommitFgColor:
      - '#4dfa2f'
    unstagedChangesColor:
      - '#ff7063'
    defaultFgColor:
      - '#ebdbb2'
    searchingActiveBorderColor:
      - '#fabd2f'
  showIcons: true
  nerdFontsVersion: "3"
